<a href="https://colab.research.google.com/github/th2l-aipn/IntroDL/blob/master/examples/0.%20Getting%20Started/Iris_Bayesian_decision_making.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Import libraries

In [0]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

import numpy as np
import time

## 2. Preparing iris dataset

In [2]:
iris = datasets.load_iris()

# get training and testing indexes randomly
train_indx = np.random.choice(range(0, 150), int(iris.target.shape[0]/100*60), replace=False)
test_indx = np.array([indx for indx in np.arange(0, 150, 1) if indx not in train_indx])

x_train = iris.data[train_indx, :]
y_train = iris.target[train_indx]

x_test = iris.data[test_indx, :]
y_test = iris.target[test_indx]

print('X train shape: ', x_train.shape)
print('y train shape: ', y_train.shape)
print('X test shape: ', x_test.shape)
print('y test shape: ', y_test.shape)

X train shape:  (90, 4)
y train shape:  (90,)
X test shape:  (60, 4)
y test shape:  (60,)


## 3. Parameters estimation

In [3]:
mu_0 = np.mean(x_train[y_train == 0], axis=0)
sigma_0 = np.cov(x_train[y_train == 0], rowvar=0)

print('Mean 0: \n\t', mu_0)
print('Covariance 0: \n\t', sigma_0, '\n')

mu_1 = np.mean(x_train[y_train == 1], axis=0)
sigma_1 = np.cov(x_train[y_train == 1], rowvar=0)
print('Mean 1: \n\t', mu_1)
print('Covariance 1: \n\t', sigma_1, '\n')

mu_2 = np.mean(x_train[y_train == 2], axis=0)
sigma_2 = np.cov(x_train[y_train == 2], rowvar=0)
print('Mean 2: \n\t', mu_2)
print('Covariance 2: \n\t', sigma_2)

Mean 0: 
	 [4.959375 3.3375   1.490625 0.265625]
Covariance 0: 
	 [[0.10829637 0.08576613 0.02767137 0.01275202]
 [0.08576613 0.11919355 0.02616935 0.01487903]
 [0.02767137 0.02616935 0.03378024 0.00740927]
 [0.01275202 0.01487903 0.00740927 0.01200605]] 

Mean 1: 
	 [6.04545455 2.84242424 4.4030303  1.36060606]
Covariance 1: 
	 [[0.23505682 0.05488636 0.09204545 0.02434659]
 [0.05488636 0.06064394 0.03642992 0.01734848]
 [0.09204545 0.03642992 0.10467803 0.03512311]
 [0.02434659 0.01734848 0.03512311 0.02558712]] 

Mean 2: 
	 [6.664 2.864 5.624 1.912]
Covariance 2: 
	 [[0.29906667 0.0424     0.27548333 0.04961667]
 [0.0424     0.06823333 0.03173333 0.03045   ]
 [0.27548333 0.03173333 0.3194     0.05386667]
 [0.04961667 0.03045    0.05386667 0.06776667]]


## 4. Bayesian decision making

In [4]:
gnb = GaussianNB()

y_pred = gnb.fit(x_train, y_train).predict(x_test)
print('Testing classification accuracy: %.4f' % ((y_test == y_pred).sum()/x_test.shape[0]))

Testing classification accuracy: 0.9667
