<a href="https://colab.research.google.com/github/th2l-aipn/IntroDL/blob/master/examples/0.%20Getting%20Started/Iris_Bayesian_decision_making.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a href="https://colab.research.google.com/github/th2l-aipn/IntroDL/blob/master/examples/0.%20Getting%20Started/Iris_Bayesian_decision_making.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Import libraries

In [0]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

import numpy as np
import time

## 2. Preparing iris dataset

In [2]:
iris = datasets.load_iris()

# get training and testing indexes randomly
train_indx = np.random.choice(range(0, 150), int(iris.target.shape[0]/100*60), replace=False)
test_indx = np.array([indx for indx in np.arange(0, 150, 1) if indx not in train_indx])

x_train = iris.data[train_indx, :]
y_train = iris.target[train_indx]

x_test = iris.data[test_indx, :]
y_test = iris.target[test_indx]

print('X train shape: ', x_train.shape)
print('y train shape: ', y_train.shape)
print('X test shape: ', x_test.shape)
print('y test shape: ', y_test.shape)

X train shape:  (90, 4)
y train shape:  (90,)
X test shape:  (60, 4)
y test shape:  (60,)


## 3. Parameters estimation

In [3]:
mu_0 = np.mean(x_train[y_train == 0], axis=0)
sigma_0 = np.cov(x_train[y_train == 0], rowvar=0)

print('Mean 0: \n\t', mu_0)
print('Covariance 0: \n\t', sigma_0, '\n')

mu_1 = np.mean(x_train[y_train == 1], axis=0)
sigma_1 = np.cov(x_train[y_train == 1], rowvar=0)
print('Mean 1: \n\t', mu_1)
print('Covariance 1: \n\t', sigma_1, '\n')

mu_2 = np.mean(x_train[y_train == 2], axis=0)
sigma_2 = np.cov(x_train[y_train == 2], rowvar=0)
print('Mean 2: \n\t', mu_2)
print('Covariance 2: \n\t', sigma_2)

Mean 0: 
	 [5.00384615 3.43076923 1.48846154 0.24615385]
Covariance 0: 
	 [[0.14838462 0.13627692 0.01284615 0.00741538]
 [0.13627692 0.19341538 0.01756923 0.00612308]
 [0.01284615 0.01756923 0.02426154 0.00295385]
 [0.00741538 0.00612308 0.00295385 0.01058462]] 

Mean 1: 
	 [5.98125  2.803125 4.303125 1.3625  ]
Covariance 1: 
	 [[0.27447581 0.10360887 0.19006048 0.06056452]
 [0.10360887 0.11966734 0.1003125  0.04915323]
 [0.19006048 0.1003125  0.24353831 0.08205645]
 [0.06056452 0.04915323 0.08205645 0.04435484]] 

Mean 2: 
	 [6.721875 3.046875 5.659375 2.040625]
Covariance 2: 
	 [[0.30757056 0.07603831 0.24672379 0.02779234]
 [0.07603831 0.11160282 0.04680444 0.04319556]
 [0.24672379 0.04680444 0.26958669 0.02234879]
 [0.02779234 0.04319556 0.02234879 0.07087702]]


## 4. Bayesian decision making

In [4]:
gnb = GaussianNB()

y_pred = gnb.fit(x_train, y_train).predict(x_test)
print('Testing classification accuracy: %.4f' % ((y_test == y_pred).sum()/x_test.shape[0]))

Testing classification accuracy: 0.9167
