<a href="https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/th2l-aipn/IntroDL/blob/master/examples/0.%20Getting%20Started/Iris_Bayesian_decision_making.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Import libraries

In [1]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

import numpy as np
import time

## 2. Preparing iris dataset

In [2]:
iris = datasets.load_iris()

# get training and testing indexes randomly
train_indx = np.random.choice(range(0, 150), int(iris.target.shape[0]/100*60), replace=False)
test_indx = np.array([indx for indx in np.arange(0, 150, 1) if indx not in train_indx])

x_train = iris.data[train_indx, :]
y_train = iris.target[train_indx]

x_test = iris.data[test_indx, :]
y_test = iris.target[test_indx]

print('X train shape: ', x_train.shape)
print('y train shape: ', y_train.shape)
print('X test shape: ', x_test.shape)
print('y test shape: ', y_test.shape)

X train shape:  (90, 4)
y train shape:  (90,)
X test shape:  (60, 4)
y test shape:  (60,)


## 3. Parameters estimation

In [3]:
mu_0 = np.mean(x_train[y_train == 0], axis=0)
sigma_0 = np.cov(x_train[y_train == 0], rowvar=0)

print('Mean 0: \n\t', mu_0)
print('Covariance 0: \n\t', sigma_0, '\n')

mu_1 = np.mean(x_train[y_train == 1], axis=0)
sigma_1 = np.cov(x_train[y_train == 1], rowvar=0)
print('Mean 1: \n\t', mu_1)
print('Covariance 1: \n\t', sigma_1, '\n')

mu_2 = np.mean(x_train[y_train == 2], axis=0)
sigma_2 = np.cov(x_train[y_train == 2], rowvar=0)
print('Mean 2: \n\t', mu_2)
print('Covariance 2: \n\t', sigma_2)

Mean 0: 
	 [4.96071429 3.37142857 1.45357143 0.23571429]
Covariance 0: 
	 [[0.12395503 0.07994709 0.0277381  0.01108466]
 [0.07994709 0.12359788 0.02010582 0.00957672]
 [0.0277381  0.02010582 0.04183862 0.00542328]
 [0.01108466 0.00957672 0.00542328 0.00830688]] 

Mean 1: 
	 [5.96571429 2.76       4.27428571 1.32285714]
Covariance 1: 
	 [[0.27114286 0.09152941 0.16968067 0.04786555]
 [0.09152941 0.11247059 0.08570588 0.04535294]
 [0.16968067 0.08570588 0.16431933 0.05560504]
 [0.04786555 0.04535294 0.05560504 0.03652101]] 

Mean 2: 
	 [6.58888889 2.96296296 5.60740741 2.0037037 ]
Covariance 2: 
	 [[0.51410256 0.15764957 0.38970085 0.05735043]
 [0.15764957 0.14242165 0.10336182 0.0512963 ]
 [0.38970085 0.10336182 0.34763533 0.04689459]
 [0.05735043 0.0512963  0.04689459 0.07729345]]


## 4. Bayesian decision making

In [4]:
gnb = GaussianNB()

y_pred = gnb.fit(x_train, y_train).predict(x_test)
print('Testing classification accuracy: %.4f' % ((y_test == y_pred).sum()/x_test.shape[0]))

Testing classification accuracy: 0.9833
